<?php include_once('header.php');?>
</div><section class="main_slider_area subsl"> <div id="main_slider" class="rev_slider" data-version="5.1.1RC"> <ul> 

    <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="2000" data-thumb="images/s1.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="" data-description=""><img src="images/s1.jpg"  alt=""  data-lazyload="images/s1.jpg" data-bgposition="left center" data-kenburns="on" data-duration="30000" data-scalestart="110" data-scaleend="100" class="rev-slidebg" data-no-retina><div class="tp-caption concept_title" id="slide-2-layer-1" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['260','430','200','170']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','330']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;"><span>«NY ho TIA</span> no anjara toerako </div><div class="tp-caption concept_title" id="slide-2-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['320','480','250','210']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','280']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">ao amin'ny Fiangonana»</div><div class="tp-caption slider_sm_heding" id="slide-2-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['440','640','330','280']" data-fontsize="['30','30','24','18']" data-lineheight="['32','32','28','20']" data-width="['680','680','550','410','410','410']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 660px; max-width: 660px; white-space: normal;">Grand séminaire théologique interdiocésain de
I'Archidocése d'Antananarivo</div> </li>
<li data-index="rs-2" data-transition="fade" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="2000" data-thumb="images/s2.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="" data-description=""><img src="images/s2.jpg"  alt=""  data-lazyload="images/s2.jpg" data-bgposition="left center" data-kenburns="on" data-duration="30000" data-scalestart="120" data-scaleend="100" class="rev-slidebg" data-no-retina><div class="tp-caption concept_title" id="slide-2-layer-1" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['260','430','200','170']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','330']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;"><span>«NY ho TIA</span> no anjara toerako </div><div class="tp-caption concept_title" id="slide-2-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['320','480','250','210']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','280']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">ao amin'ny Fiangonana»</div><div class="tp-caption slider_sm_heding" id="slide-2-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['440','640','330','280']" data-fontsize="['30','30','24','18']" data-lineheight="['32','32','28','20']" data-width="['680','680','550','410','410','410']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 660px; max-width: 660px; white-space: normal;">Grand séminaire théologique interdiocésain de
I'Archidocése d'Antananarivo</div> </li>
<li data-index="rs-3" data-transition="fade" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="2000" data-thumb="images/s3.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="" data-description=""><img src="images/s3.jpg"  alt=""  data-lazyload="images/s3.jpg" data-bgposition="left center" data-kenburns="on" data-duration="30000" data-scalestart="110" data-scaleend="100" class="rev-slidebg" data-no-retina><div class="tp-caption concept_title" id="slide-2-layer-1" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['260','430','200','170']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','330']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;"><span>«NY ho TIA</span> no anjara toerako </div><div class="tp-caption concept_title" id="slide-2-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['320','480','250','210']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','280']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">ao amin'ny Fiangonana»</div><div class="tp-caption slider_sm_heding" id="slide-2-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['440','640','330','280']" data-fontsize="['30','30','24','18']" data-lineheight="['32','32','28','20']" data-width="['680','680','550','410','410','410']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 660px; max-width: 660px; white-space: normal;">Grand séminaire théologique interdiocésain de
I'Archidocése d'Antananarivo</div> </li>
</ul>
 <div class="tp-bannertimer tp-top"></div></div></section> 

<section class="history" style="padding-top: 25px;">
	<div class="container">
<div class="tittle_2"> <h2 style="background:#fecd19;width:auto;color:#fff;font-weight:1000;display:inline-block;padding:5px 15px;margin-bottom: 30px">Galerie</h2> </div>
<div class="row">
    <div class="col-lg-4 col-md-12 wow fadeIn">
        <img src="images/im2.jpg" class="mw pb30">
        <img src="images/im1.jpg" class="mw pb30">
        <img src="church.jpg" class="mw pb30">
    </div>
    <div class="col-lg-4 col-md-12 wow fadeIn">
        <img src="a1.jpg" class="mw pb30">
        <img src="images/about-1.jpg" class="mw pb30">
    </div>
    <div class="col-lg-4 col-md-12 wow fadeIn">
        <img src="ev1.jpg" class="mw pb30">
        <img src="ev2.jpg" class="mw pb30">
        <img src="ev3.jpg" class="mw pb30">
    </div>
</div>
</div>
</section> 
<?php include_once('footer.php');?>