<?php include_once('header.php');?>
</div><section class="main_slider_area subsl"> <div id="main_slider" class="rev_slider" data-version="5.1.1RC"> <ul> 

    <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="2000" data-thumb="images/s1.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="" data-description=""><img src="images/s1.jpg"  alt=""  data-lazyload="images/s1.jpg" data-bgposition="left center" data-kenburns="on" data-duration="30000" data-scalestart="110" data-scaleend="100" class="rev-slidebg" data-no-retina><div class="tp-caption concept_title" id="slide-2-layer-1" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['260','430','200','170']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','330']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;"><span>«NY ho TIA</span> no anjara toerako </div><div class="tp-caption concept_title" id="slide-2-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['320','480','250','210']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','280']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">ao amin'ny Fiangonana»</div><div class="tp-caption slider_sm_heding" id="slide-2-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['440','640','330','280']" data-fontsize="['30','30','24','18']" data-lineheight="['32','32','28','20']" data-width="['680','680','550','410','410','410']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 660px; max-width: 660px; white-space: normal;">Grand séminaire théologique interdiocésain de
I'Archidocése d'Antananarivo</div> </li>
<li data-index="rs-2" data-transition="fade" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="2000" data-thumb="images/s2.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="" data-description=""><img src="images/s2.jpg"  alt=""  data-lazyload="images/s2.jpg" data-bgposition="left center" data-kenburns="on" data-duration="30000" data-scalestart="120" data-scaleend="100" class="rev-slidebg" data-no-retina><div class="tp-caption concept_title" id="slide-2-layer-1" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['260','430','200','170']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','330']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;"><span>«NY ho TIA</span> no anjara toerako </div><div class="tp-caption concept_title" id="slide-2-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['320','480','250','210']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','280']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">ao amin'ny Fiangonana»</div><div class="tp-caption slider_sm_heding" id="slide-2-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['440','640','330','280']" data-fontsize="['30','30','24','18']" data-lineheight="['32','32','28','20']" data-width="['680','680','550','410','410','410']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 660px; max-width: 660px; white-space: normal;">Grand séminaire théologique interdiocésain de
I'Archidocése d'Antananarivo</div> </li>
<li data-index="rs-3" data-transition="fade" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="2000" data-thumb="images/s3.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="" data-description=""><img src="images/s3.jpg"  alt=""  data-lazyload="images/s3.jpg" data-bgposition="left center" data-kenburns="on" data-duration="30000" data-scalestart="110" data-scaleend="100" class="rev-slidebg" data-no-retina><div class="tp-caption concept_title" id="slide-2-layer-1" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['260','430','200','170']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','330']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;"><span>«NY ho TIA</span> no anjara toerako </div><div class="tp-caption concept_title" id="slide-2-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['320','480','250','210']" data-fontsize="['50','50','40','30']" data-lineheight="['58','58','35','25']" data-width="['none','none','none','280']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">ao amin'ny Fiangonana»</div><div class="tp-caption slider_sm_heding" id="slide-2-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','15']" data-y="['top','top','top','top']" data-voffset="['440','640','330','280']" data-fontsize="['30','30','24','18']" data-lineheight="['32','32','28','20']" data-width="['680','680','550','410','410','410']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1000;s:1000;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 660px; max-width: 660px; white-space: normal;">Grand séminaire théologique interdiocésain de
I'Archidocése d'Antananarivo</div> </li>
</ul>
 <div class="tp-bannertimer tp-top"></div></div></section> 
 <section id="propos" class="history" style="padding-top: 25px;"> <div class="about_img"> <img src="images/about-1.jpg" alt=""> </div><div class="about_content"> <div class="content"> <h4>A PROPOS</h4> <h2>« Aimer, c’est tout donner et se donner soi-même »</h2> <p>Le Grand Séminaire « Sainte Thérèse de l’Enfant-Jésus » de Faliarivo est un Centre de formation théologique pour les jeunes qui se préparent au Sacerdoce. Ainsi, héberge-t-il pour une durée de trois ans :</p></div><div class="content_video"><div class="video_p"><p style="padding-right: 35px;text-align: justify;padding-top: 10px;">1° des Grands Séminaristes de l’Archidiocèse du Centre (Antananarivo, Antsirabe, Miarinarivo, Tsiroanomandidy et Maintirano) et ceux d’autres Archidiocèses (du Nord : Port-Bergé, Mahajanga et Ambanja ; de l’Est : Toamasina ; Fenoarivo-Atsinanana et Ambatondrazaka. <br>2° Concernant les études théologiques, le Grand Séminaire accueille aussi les jeunes de six Congrégations masculines (Montfortains ; Sainte Famille ; Salettins ; Trinitaires ; franciscains et Apôtres de la Miséricorde).
</p></div><div class=""><img src="images/about-2.jpg" style="padding-top: 22px"> </div></div></div></section>

<div style="padding: 20px 15%;text-align: center;">
	<h2 style="text-align: center;">Des séminaristes</h2>
<p style="line-height: 1.3;text-align: justify; padding-top: 20px">La formation presbytérale concerne le séminariste mais dans son parcours, il est lui-même « le protagoniste nécessaire et irremplaçable de sa formation » . Sans l’adhésion libre, consciente et volontaire du concerné aux dimensions de la formation au cheminement vers le Sacerdoce, personne ne peut accéder à la vie presbytérale. C’est en acceptant de se former que le candidat acquiert la maturité requise pour le Sacerdoce.<br><br>

Pour cette année académique 2019-2020, l’effectif total des séminaristes résidents au GSTF est de 172 dont 56 en 2ème année de Théologie, 60 en 3ème année et 56 en 4ème année. Les séminaristes de la 4ème année ont déjà reçu les ministères de lectorat et d’acolytat. Chaque séminariste assure aussi un ministère dans une école catholique (pour ceux de la 1ère année) ou dans une paroisse (pour les restes).
</p> 

<h2 style="text-align: center;padding-top: 40px">Des éducateurs</h2><div style="padding: 25px 0 0 0;margin-left: 30px; float: right;width: 50%">
<img src="pic1.jpg" style="width: 100%;">
<p style="line-height: 1.3;">Les éducateurs (Messe communautaire)</p>
</div>
<p style="line-height: 1.3;text-align: justify; padding-top: 20px"><span style="font-style: italic">L’équipe formatrice est constituée de prêtres nommés par l’Évêque diocésain avec l’approbation des autres Évêques de la circonscription ecclésiale pour le Grand Séminaire interdiocésain comme le cas du GSTF. Ces prêtres formateurs « choisis et compétents »  ont pour responsabilité d’amener chaque séminariste à percevoir ce que sera sa vie de prêtre et à commencer de la vivre.</span><br><br>
Comme le stipule la Ratio fundamentalis Institutionis Sacerdotalis , la communauté formatrice au Séminaire est composée du Recteur, d’un « coordinateur de la dimension spirituelle », d’un « coordinateur de la dimension intellectuelle » et d’un « coordinateur de la dimension humaine ». Pour qu’il y ait efficacité dans la formation, « il faut… que les formateurs soient présents à plein temps et qu’ils soient avant tout des témoins par leur amour et leur service du peuple de Dieu, en se dépensant sans compter pour l’Église » .
<br>
  Actuellement, il y a cinq Prêtres envoyés par leur respectif Evêque pour former l’équipe éducatrice au GSTF. Ils sont issus des quatre Diocèses formant la Province Ecclésiastique du Centre : Antananarivo, Antsirabe, Miarinarivo et Tsiroanomandidy.<br><br>
-	<span style="color: #deb50b; font-weight: 600;">RAHERITIANA Bruno Nicolas</span>, prêtre du diocèse d’Antananarivo, coordinateur de la dimension intellectuelle.<br>
-	<span style="color: #deb50b; font-weight: 600;">RAKOTONDRAMADY Jean-Baptiste</span>, prêtre du diocèse de Miarinarivo, économe.<br>
-	<span style="color: #deb50b; font-weight: 600;">RAFALIMANANA Jean Stephenson</span>, prêtre du diocèse de Tsiroanomandidy, coordinateur de la dimension humaine.<br>
-	<span style="color: #deb50b; font-weight: 600;">RANDRIAMANOHY Germain Julien</span>, prêtre du diocèse d’Antsirabe, coordinateur de la dimension spirituelle.<br>
-	<span style="color: #deb50b; font-weight: 600;">RAFIDISON Abdon</span>, prêtre du diocèse d’Antananarivo, Recteur.<br></p>

<p style="line-height: 1.3;text-align: justify">-	A part ces cinq Prêtres, il y a la Sœur Alice RAHARIVELO de la Congrégation « Zanaka Vavin’ny Eglizy », domiciliée à la Communauté d’Andohalo pour assurer l’intendance. L’enseignement est assuré par vingt-cinq (25) Prêtres (diocésains et religieux) et une laïque. A part tout cela, il y a aussi onze (11) personnels laïcs pour assurer d’autres services (1 secrétaire, 1 bibliothécaire, 3 cuisiniers, 2 jardiniers, 2 pour la ménage, 2 gardiens).
</p> 
<p style="font-size: 10px;line-height: 1;text-align: left;padding: 20px 0 0 0">
  1. Pastores Dabo Vobis 69. <br>
  2. Ratio Fundamentalis Institutionis Sacerdotalis 132. Cf. Directives sur la préparation des éducateurs dans les séminaires, n°1 : Enchiridion Vaticanum 13 (1996), 3151-3152.<br>
  3. CONGREGATION POUR LE CLERGE, Le don de la vocation presbytérale, 8 Décembre 2016, N° 132-139.<br>
  4. Ratio Fundamentalis Institutionis Sacerdotalis 49 ; cf. Pastores Dabo Vobis 66 : « Il est opportun qu'il jouisse d'une certaine stabilité et qu'il ait sa résidence habituelle dans la communauté du séminaire ».

</p>
</div>
<?php include_once('footer.php');?>